# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField()),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
            },
        ),
    ]
