# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startspecday', models.DateTimeField()),
                ('endspecday', models.DateTimeField(blank=True, null=True)),
                ('dateid', models.IntegerField()),
                ('yuanying', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_speday',
                'managed': False,
            },
        ),
    ]
