# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-25 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='demomination',
            new_name='denomination',
        ),
    ]
