# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0002_auto_20170125_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='denomination',
            new_name='description',
        ),
    ]
