# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('badgenumber', models.CharField(max_length=24, unique=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('pager', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('hiredday', models.DateTimeField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(blank=True, max_length=2, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=12, null=True)),
                ('ophone', models.CharField(blank=True, max_length=20, null=True)),
                ('fphone', models.CharField(blank=True, max_length=20, null=True)),
                ('verificationmethod', models.IntegerField(blank=True, null=True)),
                ('securityflags', models.IntegerField(blank=True, null=True)),
                ('att', models.IntegerField()),
                ('inlate', models.IntegerField()),
                ('outearly', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('sep', models.IntegerField()),
                ('holiday', models.IntegerField()),
                ('minzu', models.CharField(blank=True, max_length=8, null=True)),
                ('lunchduration', models.IntegerField()),
                ('mverifypass', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inheritdeptsch', models.IntegerField(blank=True, null=True)),
                ('inheritdeptschclass', models.IntegerField(blank=True, null=True)),
                ('autoschplan', models.IntegerField(blank=True, null=True)),
                ('minautoschinterval', models.IntegerField(blank=True, null=True)),
                ('registerot', models.IntegerField(blank=True, null=True)),
                ('inheritdeptrule', models.IntegerField(blank=True, null=True)),
                ('emprivilege', models.IntegerField(blank=True, null=True)),
                ('cardno', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('privilege', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
