# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkinout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checktime', models.DateTimeField()),
                ('checktype', models.CharField(blank=True, max_length=1, null=True)),
                ('verifycode', models.IntegerField(blank=True, null=True)),
                ('sensorid', models.CharField(blank=True, max_length=5, null=True)),
                ('workcode', models.IntegerField(blank=True, null=True)),
                ('sn', models.CharField(blank=True, max_length=20, null=True)),
                ('userextfmt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checkinout',
                'managed': False,
            },
        ),
    ]
