# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(blank=True, max_length=30, null=True)),
                ('supdeptid', models.IntegerField()),
                ('inheritparentsch', models.IntegerField(blank=True, null=True)),
                ('inheritdeptsch', models.IntegerField(blank=True, null=True)),
                ('inheritdeptschclass', models.IntegerField(blank=True, null=True)),
                ('autoschplan', models.IntegerField(blank=True, null=True)),
                ('inlate', models.IntegerField(blank=True, null=True)),
                ('outearly', models.IntegerField(blank=True, null=True)),
                ('inheritdeptrule', models.IntegerField(blank=True, null=True)),
                ('minautoschinterval', models.IntegerField(blank=True, null=True)),
                ('registerot', models.IntegerField(blank=True, null=True)),
                ('defaultschid', models.IntegerField(blank=True, null=True)),
                ('att', models.IntegerField(blank=True, null=True)),
                ('holiday', models.IntegerField(blank=True, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
    ]
