# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersinfo', '0002_checkinout'),
        ('years', '0001_initial'),
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fkmonth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='months.Month')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Earning',
                'verbose_name_plural': 'Earnings',
            },
        ),
        migrations.CreateModel(
            name='PayObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('concept', models.CharField(max_length=140)),
                ('pays', models.ManyToManyField(through='payobjects.Earning', to='usersinfo.Userinfo')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'PayObject',
                'verbose_name_plural': 'PayObjects',
            },
        ),
        migrations.AddField(
            model_name='earning',
            name='fkpayobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payobjects.PayObject'),
        ),
        migrations.AddField(
            model_name='earning',
            name='fkuserinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersinfo.Userinfo'),
        ),
        migrations.AddField(
            model_name='earning',
            name='fkyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.Year'),
        ),
    ]
