# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
        ('payobjects', '0002_earning_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='fkline',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='lines.Line'),
            preserve_default=False,
        ),
    ]
