# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersinfo', '0002_checkinout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fkuserinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersinfo.Userinfo')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Detail User',
                'verbose_name_plural': 'Detail Users',
            },
        ),
    ]
